### ISSUE TITLE
执行sh  show-busy-java-threads.sh -F报错

### ISSUE THREAD

**Issue by shenwenxin** [oldratlee/useful-scripts#65]
是我用户权限的问题吗？ 

```java
Fail to jstack busy(0.1%) thread(40956/0x9ffc) stack of java process(40946) under user(root).

Error attaching to process: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
sun.jvm.hotspot.debugger.DebuggerException: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
	at sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:411)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:305)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:
```

**Comment by wangdongsong** [comment]
你主机上有JVM进程吗？

**Comment by oldratlee** [comment]
@shenwenxin 

```java
Error attaching to process: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
sun.jvm.hotspot.debugger.DebuggerException: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
	at sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:411)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:305)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool
```

看起来是 执行 `jstack`出错了，比如 

- 被`jsatck`的`Java`进程坏掉了。
- `jstack`的版本过低、被`jsatck`的`Java`进程的`Java`版本不兼容

之类。

可以先直接用 `jstack`命令去操作一下 这个 `Java`进程 试试，再分析原因。

**Comment by oldratlee** [comment]
@shenwenxin 可以给一下运行过程日志

```bash
$ bash -x show-busy-java-threads
...
```
